# Generated by Django 3.0.7 on 2020-06-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
